image: python:3.9-buster

stages:
  - lint
  - test
  - deploy

cache:
  paths:
    - ~/.cache/pip/

lint-job:
  stage: lint
  script:
    - pip install -r requirements/dev.txt
    - make lint
  only:
    - main

test-job:
  stage: test
  services:
    - postgres:latest
  variables:
    DATABASE_HOST: postgres
    POSTGRES_DB: $DB_NAME
    POSTGRES_USER: $DB_USER
    POSTGRES_PASSWORD: $DB_PASSWORD
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - pip install -r requirements/dev.txt
    - export $(grep -v '^#' $CI_ENV | xargs)
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  only:
    - main

deploy-job:
  stage: deploy
  environment: production
  script:
    - chmod 600 $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /home/saydullo_dev/www && bash metsenat-fullupdate.sh"
  only:
    - main
