# Generated by Django 4.2.6 on 2023-10-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=30)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer')], max_length=8)),
                ('is_organization', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_process', 'In process'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
